M48
; DRILL file {KiCad (6.0.6-1)-1} date Wednesday, August 24, 2022 at 02:22:57 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-24T14:22:57-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-1)-1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X2.33Y-2.1
X2.33Y-3.46
X3.69Y-2.1
X3.69Y-3.46
T0
M30
